#!/bin/sh

InstallDir=$(pwd)
SolverDir=$(dirname "${InstallDir}")

cd "${SolverDir}"
wget tdo.sk/~janka/GliomaSolverHome/libs/lib-linux-64-bit/lib.tgz
tar -zxf lib.tgz
rm lib.tgz
cd lib

LIB_BASE=$(pwd)
tbb=tbb40_20120613oss
vtk=myVTK
hypre=hypre-2.10.0b

tar -zxf ${tbb}.tgz
tar -zxf ${vtk}.tgz
tar -zxf ${hypre}.tgz

rm ${tbb}.tgz
rm ${vtk}.tgz
rm ${hypre}.tgz

cd ${tbb}
make clean
make
cd ../
cd ${hypre}/src
make clean
./configure 
make install
cd ../../../

cd makefile
UserName=$(hostname -s)
cp tools.make/make.linux make.${UserName}
cp tools.make/Makefile .
cp tools.make/setup_linux.sh setup_${UserName}.sh

sed -i 's|_USER_LIB_BASE_|'"${LIB_BASE}"'|g' make.${UserName}
sed -i 's|_USER_NAME_|'"${UserName}"'|g' Makefile
sed -i 's|_USER_LIB_BASE_|'"${LIB_BASE}"'|g' setup_${UserName}.sh

source setup_${UserName}.sh

cat setup_${UserName}.sh
